# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Thu Mar  7 10:09:17 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AssetBrowser(object):
    def setupUi(self, AssetBrowser):
        AssetBrowser.setObjectName("AssetBrowser")
        AssetBrowser.resize(744, 329)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AssetBrowser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ly_main = QtWidgets.QVBoxLayout()
        self.ly_main.setObjectName("ly_main")
        self.lbl_title = QtWidgets.QLabel(AssetBrowser)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.ly_main.addWidget(self.lbl_title)
        self.ly_hierarchy = QtWidgets.QHBoxLayout()
        self.ly_hierarchy.setObjectName("ly_hierarchy")
        self.lbl_job = QtWidgets.QLabel(AssetBrowser)
        self.lbl_job.setObjectName("lbl_job")
        self.ly_hierarchy.addWidget(self.lbl_job)
        self.cmb_jobs = QtWidgets.QComboBox(AssetBrowser)
        self.cmb_jobs.setObjectName("cmb_jobs")
        self.ly_hierarchy.addWidget(self.cmb_jobs)
        self.lbl_stage = QtWidgets.QLabel(AssetBrowser)
        self.lbl_stage.setObjectName("lbl_stage")
        self.ly_hierarchy.addWidget(self.lbl_stage)
        self.cmb_stages = QtWidgets.QComboBox(AssetBrowser)
        self.cmb_stages.setObjectName("cmb_stages")
        self.ly_hierarchy.addWidget(self.cmb_stages)
        self.lbl_entity = QtWidgets.QLabel(AssetBrowser)
        self.lbl_entity.setObjectName("lbl_entity")
        self.ly_hierarchy.addWidget(self.lbl_entity)
        self.cmb_entities = QtWidgets.QComboBox(AssetBrowser)
        self.cmb_entities.setObjectName("cmb_entities")
        self.ly_hierarchy.addWidget(self.cmb_entities)
        self.ly_main.addLayout(self.ly_hierarchy)
        self.ly_in = QtWidgets.QHBoxLayout()
        self.ly_in.setObjectName("ly_in")
        self.le_in = CustomLineEdit(AssetBrowser)
        self.le_in.setObjectName("le_in")
        self.ly_in.addWidget(self.le_in)
        self.ly_main.addLayout(self.ly_in)
        self.ly_table = QtWidgets.QHBoxLayout()
        self.ly_table.setObjectName("ly_table")
        self.tbl_assets = QtWidgets.QTableWidget(AssetBrowser)
        self.tbl_assets.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbl_assets.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_assets.setObjectName("tbl_assets")
        self.tbl_assets.setColumnCount(7)
        self.tbl_assets.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_assets.setHorizontalHeaderItem(6, item)
        self.tbl_assets.horizontalHeader().setHighlightSections(False)
        self.tbl_assets.horizontalHeader().setStretchLastSection(True)
        self.tbl_assets.verticalHeader().setVisible(False)
        self.tbl_assets.verticalHeader().setHighlightSections(False)
        self.ly_table.addWidget(self.tbl_assets)
        self.ly_main.addLayout(self.ly_table)
        self.btn_import = QtWidgets.QPushButton(AssetBrowser)
        self.btn_import.setObjectName("btn_import")
        self.ly_main.addWidget(self.btn_import)
        self.verticalLayout_2.addLayout(self.ly_main)

        self.retranslateUi(AssetBrowser)
        QtCore.QMetaObject.connectSlotsByName(AssetBrowser)

    def retranslateUi(self, AssetBrowser):
        _translate = QtCore.QCoreApplication.translate
        AssetBrowser.setWindowTitle(_translate("AssetBrowser", "TBA Asset Browser"))
        self.lbl_title.setText(_translate("AssetBrowser", "Asset Browser"))
        self.lbl_job.setText(_translate("AssetBrowser", "Job:"))
        self.lbl_stage.setText(_translate("AssetBrowser", "Stage:"))
        self.lbl_entity.setText(_translate("AssetBrowser", "Entity:"))
        item = self.tbl_assets.horizontalHeaderItem(0)
        item.setText(_translate("AssetBrowser", "Asset"))
        item = self.tbl_assets.horizontalHeaderItem(1)
        item.setText(_translate("AssetBrowser", "Model"))
        item = self.tbl_assets.horizontalHeaderItem(2)
        item.setText(_translate("AssetBrowser", "Layout"))
        item = self.tbl_assets.horizontalHeaderItem(3)
        item.setText(_translate("AssetBrowser", "Anim"))
        item = self.tbl_assets.horizontalHeaderItem(4)
        item.setText(_translate("AssetBrowser", "FX (Prep)"))
        item = self.tbl_assets.horizontalHeaderItem(5)
        item.setText(_translate("AssetBrowser", "FX (Sim)"))
        item = self.tbl_assets.horizontalHeaderItem(6)
        item.setText(_translate("AssetBrowser", "Shader"))
        self.btn_import.setText(_translate("AssetBrowser", "Import Asset"))

from CustomLineEdit import CustomLineEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AssetBrowser = QtWidgets.QWidget()
    ui = Ui_AssetBrowser()
    ui.setupUi(AssetBrowser)
    AssetBrowser.show()
    sys.exit(app.exec_())

